### ISSUE TITLE
lsf numbers before filenames

### ISSUE THREAD

**Issue by a-bateman** [a-bateman/clips#9]
File names are preceded by numbers and/or symbols.  I will attempt to debug this.  Will also run on Fedora in virtualbox to see if this is an OS specific issue.

![lfs-symbols-numbers](https://user-images.githubusercontent.com/36204159/49559761-c3364080-f907-11e8-958f-1e8cf1bc8535.png)

**Comment by Wittmaxi** [comment]
This issue is not caused by us but by the ColorINK library which has been fixed.
Please update your ColorInk version!
